In [1]:
import os
import random
import pandas as pd

In [2]:
input_data = './all_hdd.csv'
output_base_path = './backblaze_HDD/'
output_path_test = './backblaze_HDD/testing/test_backblazeHDD/'
output_name_rul_end_test = './backblaze_HDD/testing/RUL_test_backblazeHDD.txt'

In [3]:
os.makedirs(output_path_test, exist_ok=True)

In [4]:
df = pd.read_csv(input_data)
display(df)

,date,serial_number,model,failure,smart_7_raw,smart_9_raw,smart_240_raw,smart_241_raw,smart_242_raw,smart_7_norm,smart_9_norm,smart_240_norm,smart_241_norm,smart_242_norm
0,2020-03-15,S300VLG3,ST4000DM000,0,5.283138e+11,40867.0,40681.0,6.213072e+10,1.337465e+11,-1.642732,-1.693239,-1.693955,-1.872728,-1.743543
1,2020-03-16,S300VLG3,ST4000DM000,0,5.454949e+11,40891.0,40705.0,6.214421e+10,1.337805e+11,-1.593933,-1.636844,-1.637556,-1.824296,-1.684765
2,2020-03-17,S300VLG3,ST4000DM000,0,5.626759e+11,40915.0,40730.0,6.215147e+10,1.338106e+11,-1.545135,-1.580449,-1.578806,-1.798240,-1.632772
3,2020-03-18,S300VLG3,ST4000DM000,0,6.013319e+11,40940.0,40754.0,6.216890e+10,1.338468e+11,-1.435342,-1.521704,-1.522406,-1.735724,-1.570274
4,2020-03-19,S300VLG3,ST4000DM000,0,6.099230e+11,40964.0,40778.0,6.221802e+10,1.338939e+11,-1.410941,-1.465309,-1.466007,-1.559443,-1.489024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7254,2020-06-12,Z307SWMC,ST4000DM000,0,5.699374e+08,25033.0,25024.0,2.569414e+10,1.669457e+11,1.411796,1.463165,1.463191,1.545999,1.510014
7255,2020-06-13,Z307SWMC,ST4000DM000,0,5.710418e+08,25057.0,25048.0,2.570304e+10,1.670785e+11,1.503492,1.519484,1.519546,1.592016,1.545573
7256,2020-06-14,Z307SWMC,ST4000DM000,0,5.720580e+08,25081.0,25072.0,2.571307e+10,1.672999e+11,1.587873,1.575802,1.575901,1.643891,1.604874
7257,2020-06-15,Z307SWMC,ST4000DM000,0,5.725869e+08,25105.0,25096.0,2.572285e+10,1.674658e+11,1.631781,1.632121,1.632256,1.694485,1.649323
7258,2020-06-16,Z307SWMC,ST4000DM000,1,5.734605e+08,25129.0,25120.0,2.573582e+10,1.675341e+11,1.704314,1.688439,1.688611,1.761567,1.667625

In [5]:
df = df[['date','serial_number','failure', 'smart_7_norm', 'smart_9_norm', 'smart_240_norm', 'smart_241_norm', 'smart_242_norm']]

In [6]:
df['date'] = pd.to_datetime(df['date'])
df['date'] = df['date'].map(lambda x: x.timestamp())

In [7]:
df['serial_number'].nunique()

119

In [8]:
df.isna().sum()

date              0
serial_number     0
failure           0
smart_7_norm      0
smart_9_norm      0
smart_240_norm    0
smart_241_norm    0
smart_242_norm    0
dtype: int64

In [9]:
df.head(10)

,date,serial_number,failure,smart_7_norm,smart_9_norm,smart_240_norm,smart_241_norm,smart_242_norm
0,1.584230e+09,S300VLG3,0,-1.642732,-1.693239,-1.693955,-1.872728,-1.743543
1,1.584317e+09,S300VLG3,0,-1.593933,-1.636844,-1.637556,-1.824296,-1.684765
2,1.584403e+09,S300VLG3,0,-1.545135,-1.580449,-1.578806,-1.798240,-1.632772
3,1.584490e+09,S300VLG3,0,-1.435342,-1.521704,-1.522406,-1.735724,-1.570274
4,1.584576e+09,S300VLG3,0,-1.410941,-1.465309,-1.466007,-1.559443,-1.489024
5,1.584662e+09,S300VLG3,0,-1.398739,-1.408914,-1.409607,-1.420596,-1.412022
6,1.584749e+09,S300VLG3,0,-1.337741,-1.352519,-1.350857,-1.358221,-1.349239
7,1.584835e+09,S300VLG3,0,-1.288942,-1.293774,-1.294458,-1.309795,-1.275972
8,1.584922e+09,S300VLG3,0,-1.240145,-1.230330,-1.231008,-1.282195,-1.223586
9,1.585008e+09,S300VLG3,0,-1.227943,-1.176284,-1.174608,-1.196495,-1.164832

In [10]:
random.seed(0)
train_list = random.sample(list(df['serial_number'].unique()), 90)
test_list = list(set(df['serial_number'].unique()) - set(train_list)) #train_list以外の残り件数を抽出

In [11]:
test_list

['Z304JNST',
 'Z304HSB0',
 'Z304JPNA',
 'S300YQ5V',
 'S300YQ0H',
 'Z302RPCT',
 'Z304K6EG',
 'S301MGPM',
 'Z302T882',
 'Z304JDAL',
 'Z304JMDW',
 'S301N6GS',
 'Z302T6R9',
 'Z305GVT3',
 'S300ZV6H',
 'S301NH6F',
 'Z304JY56',
 'Z302SWPP',
 'S301GPPH',
 'Z304KBNT',
 'S301L7TR',
 'Z302SND3',
 'Z305D5DW',
 'Z305B832',
 'Z305ANWQ',
 'S301NGVZ',
 'Z302SXNQ',
 'Z3059NCZ',
 'Z305DFMP']

In [12]:
for i in range(1,11):
    random.seed(i)
    
    train_list_supervised = random.sample(train_list, 4)
    train_list_unsupervised = list(set(train_list) - set(train_list_supervised))
    
    current_dir = 'training_semi_uniform_1_10_'+str(i)
    output_path_supervised = os.path.join(output_base_path, current_dir, 'supervised')
    output_path_unsupervised = os.path.join(output_base_path, current_dir, 'unsupervised')
    output_name_rul_end = os.path.join(output_base_path, current_dir, 'RUL_end_unsupervised.txt')
    os.makedirs(output_path_supervised, exist_ok=True)
    os.makedirs(output_path_unsupervised, exist_ok=True)
    
    #train_supervised
    for j,name in enumerate(train_list_supervised):
        tmp = df.query('serial_number == @name')[['date','smart_7_norm','smart_9_norm','smart_240_norm','smart_241_norm','smart_242_norm']].sort_values('date')
        tmp.to_csv(os.path.join(output_path_supervised,str(j+1)+'.csv'), index=False)
        
    ## train_unsupervised
    rul_end_supervised = []
    for j,name in enumerate(train_list_unsupervised):
        tmp = df.query('serial_number == @name')[['date','smart_7_norm','smart_9_norm','smart_240_norm','smart_241_norm','smart_242_norm']].sort_values('date')
        random.seed(80*i+j+1)
        del_num = random.randint(1, 10)

        tmp = tmp[:-del_num]
        rul_end_supervised.append(del_num)
        tmp.to_csv(os.path.join(output_path_unsupervised,str(j+1)+'.csv'), index=False)

    with open(output_name_rul_end, mode='w') as f:
        rul_end_supervised = [str(v) for v in rul_end_supervised]
        f.write('\n'.join(rul_end_supervised))

In [13]:
rul_end_test = []
for i,name in enumerate(test_list):
    tmp = df.query('serial_number == @name')[['date','smart_7_norm','smart_9_norm','smart_240_norm','smart_241_norm','smart_242_norm']].sort_values('date')
    random.seed(i*100)
    del_num = random.randint(1, 10)
    
    tmp = tmp[:-del_num]
    rul_end_test.append(del_num)
    
    tmp.to_csv(output_path_test+str(i+1)+'.csv', index=False)

with open(output_name_rul_end_test, mode='w') as f:
    rul_end_test = [str(v) for v in rul_end_test]
    f.write('\n'.join(rul_end_test))